from pathlib import Path
base=Path('/tmp/fieldsmove')
for rel in ['src/pages/education.astro','src/src/pages/education.astro']:
    p=base/rel
    t=p.read_text()
    t=t.replace('  const assignmentClassSelect = document.getElementById("assignment-class");\n  const assignmentWeightInput = document.getElementById("assignment-weight");\n',
                '  const assignmentClassSelect = document.getElementById("assignment-class");\n  const assignmentStartTimeInput = document.getElementById("assignment-start-time");\n  const assignmentDueTimeInput = document.getElementById("assignment-due-time");\n  const assignmentWeightInput = document.getElementById("assignment-weight");\n')
    t=t.replace('  function formatDate(dateStr) {\n    const date = parseDate(dateStr);\n    if (!date) return "No date";\n    return date.toLocaleDateString("en-US", {\n      month: "short",\n      day: "numeric",\n      year: "numeric",\n    });\n  }\n\n  function sortAssignments(items) {\n',
                '  function formatDate(dateStr) {\n    const date = parseDate(dateStr);\n    if (!date) return "No date";\n    return date.toLocaleDateString("en-US", {\n      month: "short",\n      day: "numeric",\n      year: "numeric",\n    });\n  }\n\n  function parseTimeValue(value) {\n    if (!value) return null;\n    const [hours, minutes] = value.split(":");\n    const hour = Number(hours);\n    const minute = Number(minutes);\n    if (!Number.isFinite(hour) || !Number.isFinite(minute)) return null;\n    return hour * 60 + minute;\n  }\n\n  function formatTime(value) {\n    if (!value) return "";\n    const [hours, minutes] = value.split(":");\n    const date = new Date();\n    date.setHours(Number(hours || 0), Number(minutes || 0), 0, 0);\n    return date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });\n  }\n\n  function getAssignmentSortValue(item) {\n    const dateValue = parseDate(item.dueDate)?.getTime() ?? Number.MAX_SAFE_INTEGER;\n    const timeValue = parseTimeValue(item.startTime) ?? parseTimeValue(item.dueTime) ?? Number.MAX_SAFE_INTEGER;\n    return dateValue * 1440 + timeValue;\n  }\n\n  function buildAssignmentTimeMeta(item) {\n    return [\n      item.startTime ? `Starts ${formatTime(item.startTime)}` : "",\n      item.dueTime ? `Due ${formatTime(item.dueTime)}` : "",\n    ].filter(Boolean);\n  }\n\n  function sortAssignments(items) {\n')
    t=t.replace('            <span>${escapeHtml(dueText)}</span>\n            <span>${escapeHtml(formatDate(item.dueDate))}</span>\n            ${item.weight ? `<span>${escapeHtml(item.weight)}% of grade</span>` : ""}\n',
                '            <span>${escapeHtml(dueText)}</span>\n            <span>${escapeHtml(formatDate(item.dueDate))}</span>\n            ${buildAssignmentTimeMeta(item).map((label) => `<span>${escapeHtml(label)}</span>`).join("")}\n            ${item.weight ? `<span>${escapeHtml(item.weight)}% of grade</span>` : ""}\n')
    t=t.replace('    const dueDate = assignmentDueInput.value;\n    const classId = assignmentClassSelect.value;\n    const weight = assignmentWeightInput.value.trim();\n\n    if (!name || !dueDate || !classId) return;\n\n    assignments.push({\n      id: makeId(),\n      name,\n      dueDate,\n      classId,\n      weight: weight ? Number(weight) : null,\n      completed: false,\n      createdAt: new Date().toISOString(),\n    });\n',
                '    const dueDate = assignmentDueInput.value;\n    const startTime = assignmentStartTimeInput?.value || "";\n    const dueTime = assignmentDueTimeInput?.value || "";\n    const classId = assignmentClassSelect.value;\n    const weight = assignmentWeightInput.value.trim();\n\n    if (!name || !dueDate || !classId) return;\n\n    assignments.push({\n      id: makeId(),\n      name,\n      dueDate,\n      startTime: startTime || null,\n      dueTime: dueTime || null,\n      classId,\n      weight: weight ? Number(weight) : null,\n      completed: false,\n      createdAt: new Date().toISOString(),\n    });\n')
    p.write_text(t)
print('fixed inline pages')
