import type { RendererPageConfig } from '../../types/ui';
import { sharedTagColors } from './sharedColors';

export const workPageKey = 'work';

export const defaultWorkState = {
  projects: [
    { id: 'work-internal', name: 'Internal', color: '#2f5d62' },
    { id: 'work-client', name: 'Client Work', color: '#2563eb' },
    { id: 'work-meetings', name: 'Meetings', color: '#6a3fa0' },
  ],
  tasks: [],
  meetings: [],
  removedDefaults: {
    projects: [],
  },
} as const;

export const workPageConfig: RendererPageConfig = {
  hero: {
    kicker: 'Work',
    title: 'Work dashboard',
    description: 'Track projects, tasks, meetings, and the work that needs attention first.',
  },
  sections: [
    {
      kind: 'surface-target',
      key: 'due-this-week',
      title: 'Due This Week',
      subtitle: 'Closest deadlines first.',
      containerId: 'due-this-week',
      containerClassName: 'education-list',
      cardClassName: 'education-panel',
      sectionClassName: 'education-shell',
    },
    {
      kind: 'surface-target',
      key: 'upcoming-meetings',
      title: 'Upcoming Meetings',
      subtitle: 'Today and next on deck.',
      containerId: 'meetings-list',
      containerClassName: 'education-list',
      cardClassName: 'education-panel',
      sectionClassName: 'education-shell',
    },
    {
      kind: 'surface-target',
      key: 'all-upcoming',
      title: 'All Upcoming Tasks',
      subtitle: 'Sorted by due date and time.',
      containerId: 'all-upcoming',
      containerClassName: 'education-list',
      cardClassName: 'education-panel',
      sectionClassName: 'education-shell',
    },
    {
      kind: 'form-card',
      key: 'task-form',
      title: 'Add Task',
      subtitle: 'Add work by section, deadline, and priority.',
      sectionClassName: 'education-shell',
      fieldsWrapperClassName: 'edu-form-grid',
      form: {
        id: 'task-form',
        fields: [
          { id: 'task-title', name: 'taskTitle', label: 'Task name', placeholder: 'Send revised proposal', required: true, className: 'edu-label', inputClassName: 'text-input' },
          { id: 'task-due-date', name: 'taskDueDate', type: 'date', label: 'Due date', required: true, className: 'edu-label', inputClassName: 'text-input' },
          { id: 'task-due-time', name: 'taskDueTime', type: 'time', label: 'Due time', className: 'edu-label', inputClassName: 'text-input' },
          { id: 'task-project', name: 'taskProject', type: 'select', label: 'Section', required: true, className: 'edu-label', inputClassName: 'text-input', options: [{ value: '', label: 'Select a section' }] },
          { id: 'task-priority', name: 'taskPriority', type: 'select', label: 'Priority', className: 'edu-label', inputClassName: 'text-input', value: 'medium', options: [
            { value: 'medium', label: 'Medium' },
            { value: 'low', label: 'Low' },
            { value: 'high', label: 'High' },
            { value: 'urgent', label: 'Urgent' },
          ] },
          { id: 'task-status', name: 'taskStatus', type: 'select', label: 'Status', className: 'edu-label', inputClassName: 'text-input', value: 'todo', options: [
            { value: 'todo', label: 'To do' },
            { value: 'in-progress', label: 'In progress' },
            { value: 'blocked', label: 'Blocked' },
            { value: 'done', label: 'Done' },
          ] },
          { id: 'task-estimated-hours', name: 'taskEstimatedHours', type: 'number', label: 'Estimated hours', min: 0, step: 0.5, placeholder: '2', className: 'edu-label', inputClassName: 'text-input' },
          { id: 'task-notes', name: 'taskNotes', type: 'textarea', label: 'Notes', rows: 4, placeholder: 'Context, next steps, blockers, links...', className: 'edu-label edu-label-full', inputClassName: 'text-input' },
        ],
        actions: [{ label: 'Add Task', type: 'submit', variant: 'primary' }],
      },
    },
    {
      kind: 'form-card',
      key: 'meeting-form',
      title: 'Add Meeting',
      subtitle: 'Schedule meetings and keep them grouped by section.',
      sectionClassName: 'education-shell',
      fieldsWrapperClassName: 'edu-form-grid',
      form: {
        id: 'meeting-form',
        fields: [
          { id: 'meeting-title', name: 'meetingTitle', label: 'Meeting title', placeholder: 'Weekly team sync', required: true, className: 'edu-label', inputClassName: 'text-input' },
          { id: 'meeting-date', name: 'meetingDate', type: 'date', label: 'Date', required: true, className: 'edu-label', inputClassName: 'text-input' },
          { id: 'meeting-start', name: 'meetingStart', type: 'time', label: 'Start time', required: true, className: 'edu-label', inputClassName: 'text-input' },
          { id: 'meeting-end', name: 'meetingEnd', type: 'time', label: 'End time', required: true, className: 'edu-label', inputClassName: 'text-input' },
          { id: 'meeting-project', name: 'meetingProject', type: 'select', label: 'Section', className: 'edu-label', inputClassName: 'text-input', options: [{ value: '', label: 'No section' }] },
          { id: 'meeting-location', name: 'meetingLocation', label: 'Location / link', placeholder: 'Zoom, Room 204, Meet link...', className: 'edu-label', inputClassName: 'text-input' },
          { id: 'meeting-notes', name: 'meetingNotes', type: 'textarea', label: 'Notes', rows: 4, placeholder: 'Agenda, attendees, prep notes...', className: 'edu-label edu-label-full', inputClassName: 'text-input' },
        ],
        actions: [{ label: 'Add Meeting', type: 'submit', variant: 'primary' }],
      },
    },
    {
      kind: 'color-managed-list',
      key: 'projects',
      title: 'Sections',
      subtitle: 'Group your tasks and meetings by team, client, or workstream.',
      sectionClassName: 'education-shell',
      cardClassName: 'education-panel',
      listId: 'project-list',
      listClassName: 'class-list',
      restoreAction: { label: 'Restore Defaults', id: 'restore-projects-btn', type: 'button', variant: 'secondary' },
      form: {
        id: 'project-form',
        fields: [
          { id: 'project-name', name: 'projectName', label: 'Section name', placeholder: 'Client Onboarding', required: true, className: 'edu-label', inputClassName: 'text-input' },
        ],
        actions: [{ label: 'Add Section', type: 'submit', variant: 'primary' }],
      },
      formFieldsWrapperClassName: 'edu-form-grid class-grid',
      colorFieldWrapperClassName: 'edu-label',
      colorFieldId: 'project-color',
      colorFieldName: 'projectColor',
      colorPickerId: 'project-color-picker',
      colorLabel: 'Color',
      colorOptions: [...sharedTagColors],
      defaultColor: '#2f5d62',
    },
    {
      kind: 'expandable-target',
      key: 'completed',
      title: 'Completed Tasks',
      open: false,
      sectionClassName: 'education-shell',
      bodyClassName: 'completed-panel',
      containerId: 'completed-list',
      containerClassName: 'education-list completed-list',
      countBadgeId: 'completed-count',
      countBadgeClassName: 'completed-count',
      countBadgeText: '0',
    },
  ],
};

export const workClientConfig = {
  pageKey: workPageKey,
  defaultColor: '#2f5d62',
  defaults: defaultWorkState,
  sections: {
    projects: {
      taskSelectId: 'task-project',
      meetingSelectId: 'meeting-project',
      formId: 'project-form',
      nameInputId: 'project-name',
      colorInputId: 'project-color',
      colorPickerId: 'project-color-picker',
      restoreButtonId: 'restore-projects-btn',
      listId: 'project-list',
      emptyText: 'No sections yet.',
    },
    tasks: {
      formId: 'task-form',
      titleInputId: 'task-title',
      dueDateInputId: 'task-due-date',
      dueTimeInputId: 'task-due-time',
      projectSelectId: 'task-project',
      priorityInputId: 'task-priority',
      statusInputId: 'task-status',
      estimatedHoursInputId: 'task-estimated-hours',
      notesInputId: 'task-notes',
      dueThisWeekId: 'due-this-week',
      allUpcomingId: 'all-upcoming',
      completedListId: 'completed-list',
      completedCountId: 'completed-count',
    },
    meetings: {
      formId: 'meeting-form',
      titleInputId: 'meeting-title',
      dateInputId: 'meeting-date',
      startInputId: 'meeting-start',
      endInputId: 'meeting-end',
      projectSelectId: 'meeting-project',
      locationInputId: 'meeting-location',
      notesInputId: 'meeting-notes',
      listId: 'meetings-list',
    },
  },
};
